// Generates supabase/seed.sql from the bundled seed data so the database matches
// the offline fallback exactly. Run with:
//   node --experimental-strip-types scripts/gen-seed.mts > supabase/seed.sql
//
// (src/lib/mock/data.ts only uses type-only imports, so type-stripping makes it
// loadable directly by Node.)

import * as mock from "../src/lib/mock/data.ts";
import { admins } from "../src/lib/mock/admin.ts";

type Row = Record<string, unknown>;

function sql(v: unknown): string {
  if (v === null || v === undefined) return "null";
  if (typeof v === "number") return String(v);
  if (typeof v === "boolean") return v ? "true" : "false";
  return "'" + String(v).replace(/'/g, "''") + "'";
}

function insert(table: string, cols: string[], rows: Row[]): string {
  if (rows.length === 0) return "";
  const values = rows
    .map((r) => "  (" + cols.map((c) => sql(r[c])).join(", ") + ")")
    .join(",\n");
  return (
    `insert into ${table} (${cols.join(", ")}) values\n${values}\n` +
    `on conflict (id) do nothing;\n`
  );
}

const blocks: string[] = [
  "-- AUTO-GENERATED by scripts/gen-seed.mts — do not edit by hand.",
  "-- Seed data for the GUIYE 瑰野 console. Run after 0001_init.sql.",
  "",
  "begin;",
  "",
  insert("warehouses", ["id", "name", "code", "region"], mock.warehouses),
  insert(
    "products",
    ["id", "sku_code", "name", "category", "price", "cost", "safety_stock", "status"],
    mock.products,
  ),
  insert(
    "inventory",
    ["id", "product_id", "warehouse_id", "sellable", "locked", "transit", "safety_stock"],
    mock.inventory,
  ),
  insert(
    "dealers",
    ["id", "name", "region", "contact", "level", "status", "contract_end", "credit_limit", "debt", "mtd_sales", "created_at"],
    mock.dealers,
  ),
  insert(
    "customers",
    ["id", "name", "country", "email", "phone", "type", "level", "orders_count", "total_spent", "last_order_at", "created_at"],
    mock.customers,
  ),
  insert(
    "orders",
    ["id", "order_no", "customer_name", "country", "order_type", "order_channel", "customer_source", "payment_method", "source", "ship_from", "amount", "amount_received", "pay_status", "fulfill_status", "settle_status", "status", "created_at"],
    mock.orders,
  ),
  insert("order_items", ["id", "order_id", "product_name", "sku_code", "qty", "price"], mock.orderItems),
  insert(
    "shipments",
    ["id", "order_no", "carrier", "tracking_no", "destination", "status", "exception", "shipped_at"],
    mock.shipments,
  ),
  insert(
    "settlements",
    ["id", "ref_no", "type", "party", "amount", "status", "due_date", "created_at"],
    mock.settlements,
  ),
  insert("brand_assets", ["id", "title", "category", "kind", "size", "updated_at"], mock.brandAssets),
  insert("system_users", ["id", "name", "email", "role", "status", "last_active"], mock.systemUsers),
  insert(
    "payments",
    ["id", "order_no", "txn_no", "method", "merchant_no", "amount_due", "amount_paid", "fee", "pay_status", "paid_at", "arrived", "settle_status", "refunded"],
    mock.payments,
  ),
  insert(
    "refunds",
    ["id", "order_no", "refund_no", "origin_txn_no", "method", "applied_amount", "actual_amount", "reason", "operator", "applied_at", "arrived_at", "partial", "status"],
    mock.refunds,
  ),
  insert(
    "admins",
    ["id", "name", "phone", "email", "level", "role", "dept", "scope", "scope_label", "status", "last_login"],
    admins,
  ),
  "commit;",
  "",
];

process.stdout.write(blocks.join("\n"));
